### get de docentes
GET http://localhost:4000/docentes

### post de docentes
POST http://localhost:4000/docentes/registro
Content-Type: application/json

{
  "nombre": "Juan Pélaes",
  "apellido": "González López",
  "correo": "juane.peerez@umss.edu.bo",
  "contraseña": "Contraseña1"
}

### post de estudiantes
POST http://localhost:4000/estudiantes/registro
Content-Type: application/json

{
  "codigo_sis": "20211036",
  "nombres": "Lola",
  "apellidos": "Rojas",
  "correo": "ll11hhb@umss.edu.bo",
  "contraseña": "Contraseña123"
}

### get de estudliantes
GET http://localhost:4000/estudiantes

